package Prin;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ADMINISTRADOR1
 */
public class Principal extends javax.swing.JFrame {
    
    static ArrayList<Personaje> per = new ArrayList();
    static Random r = new Random();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        bt_crear_personaje.setBackground(Color.CYAN);
        try {
            admc.cargarArchivo();
            
            for (Clerigo t : admc.getListaClerigos()) {
                per.add(t);
            }

        } catch (Exception e) {
        }

        try {
            admB.cargarArchivo();
            for (Barbaro t : admB.getListaBarbaros()) {
                per.add(t);
            }
        } catch (Exception e) {
        }

        try {
            admM.cargarArchivo();
            for (Mago t : admM.getListaMagos()) {
                per.add(t);
            }

        } catch (Exception e) {
        }

        try {
            admP.cargarArchivo();
            for (Picaro t : admP.getListaPicaros()) {
                per.add(t);
            }
        } catch (Exception e) {
        }
        
        for (int i = 0; i < per.size(); i++) {
            System.out.println(per.get(i));
        }
         DefaultListModel  modelo_combo = ( DefaultListModel ) jl.getModel();
        for (int i = 0; i < per.size(); i++) {
            modelo_combo.addElement(per.get(i).getNombre());
        }
        jl.setModel(modelo_combo);
        

        DefaultComboBoxModel modelo_clase = (DefaultComboBoxModel) cb_clase.getModel();
        modelo_clase.addElement("Clerigo");
        modelo_clase.addElement("Barbaro");
        modelo_clase.addElement("Mago");
        modelo_clase.addElement("Picaro");
        cb_clase.setModel(modelo_clase);
        
        DefaultComboBoxModel modelo_listar = (DefaultComboBoxModel) cb_listar.getModel();
        modelo_listar.addElement("Clerigo");
        modelo_listar.addElement("Barbaro");
        modelo_listar.addElement("Mago");
        modelo_listar.addElement("Picaro");
        cb_listar.setModel(modelo_listar);
        
        DefaultComboBoxModel modelo_nacionalidad = (DefaultComboBoxModel) cb_nac.getModel();
        modelo_nacionalidad.addElement("Norfair");
        modelo_nacionalidad.addElement("Brinstar");
        modelo_nacionalidad.addElement("Maridia");
        modelo_nacionalidad.addElement("Zebes");
        modelo_nacionalidad.addElement("Crateria");
        cb_nac.setModel(modelo_nacionalidad);
        
        DefaultComboBoxModel modelo_raza = (DefaultComboBoxModel) cb_raza.getModel();
        modelo_raza.addElement("Mediano");
        modelo_raza.addElement("Enano");
        modelo_raza.addElement("Elfo");
        modelo_raza.addElement("Humano");
        cb_raza.setModel(modelo_raza);
        
        DefaultComboBoxModel modelo_tipo = (DefaultComboBoxModel) cb_tipo.getModel();
        modelo_tipo.addElement("Lead");
        modelo_tipo.addElement("Support");
        modelo_tipo.addElement("Offensive");
        modelo_tipo.addElement("Spammer");
        modelo_tipo.addElement("Tank");
        cb_tipo.setModel(modelo_tipo);
        
        DefaultComboBoxModel modelo_arma = (DefaultComboBoxModel) cb_arma.getModel();
        modelo_arma.addElement("Pesada");
        modelo_arma.addElement("Ligera");
        modelo_arma.addElement("Escudo");
        cb_arma.setModel(modelo_arma);
        
        DefaultComboBoxModel modelo_magia = (DefaultComboBoxModel) cb_magia.getModel();
        modelo_magia.addElement("Mago Blanco");
        modelo_magia.addElement("Mago Negro");
        modelo_magia.addElement("Sanador");
        cb_magia.setModel(modelo_magia);
        
        DefaultComboBoxModel modelo_ins = (DefaultComboBoxModel) cb_ins.getModel();
        modelo_ins.addElement("Amuleto");
        modelo_ins.addElement("Arma");
        modelo_ins.addElement("Piedra");
        cb_ins.setModel(modelo_ins);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cb_raza = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jt_Descripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cb_nac = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<>();
        cb_clase = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        bt_crear_personaje = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jft_estatura = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jft_peso = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jft_edad = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jt_dios = new javax.swing.JTextField();
        jt_invo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nv_xp = new javax.swing.JFormattedTextField();
        cb_arma = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cb_magia = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cb_ins = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cant_robo = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        cb_listar = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_eliminar = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabStateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel1.setText("Personajes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 81, -1));

        jPanel1.add(cb_raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 119, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        jPanel1.add(jt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 104, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel3.setText("Raza");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel4.setText("Descripcion");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));
        jPanel1.add(jt_Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 145, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel5.setText("Nacionalidad");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, -1, -1));

        jPanel1.add(cb_nac, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 104, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel6.setText("Clase");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));

        jPanel1.add(cb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 121, -1));

        cb_clase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_claseItemStateChanged(evt);
            }
        });
        jPanel1.add(cb_clase, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 115, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel7.setText("Tipo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        bt_crear_personaje.setBackground(new java.awt.Color(0, 255, 255));
        bt_crear_personaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_crear_personaje.setText("Crear");
        bt_crear_personaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crear_personajeMouseClicked(evt);
            }
        });
        jPanel1.add(bt_crear_personaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 430, 60));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel8.setText("Estatura");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        jft_estatura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        jPanel1.add(jft_estatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 145, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel9.setText("Peso");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 34, -1));

        jft_peso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####"))));
        jPanel1.add(jft_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 124, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel10.setText("Edad");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jft_edad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("########"))));
        jPanel1.add(jft_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 125, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel11.setText("Dios");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));
        jPanel1.add(jt_dios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 100, -1));
        jPanel1.add(jt_invo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 100, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel12.setText("Invocacion");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel13.setText("Nivel XP");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        nv_xp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        jPanel1.add(nv_xp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 100, -1));

        jPanel1.add(cb_arma, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 292, 100, 20));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel14.setText("Arma");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel15.setText("Tipo de Magia");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        jPanel1.add(cb_magia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 140, 20));

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel16.setText("Tipo Instrumento");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));

        jPanel1.add(cb_ins, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 120, -1));

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel17.setText("Cantidad de Robos");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, -1));

        cant_robo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####"))));
        jPanel1.add(cant_robo, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 350, 110, -1));

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel18.setText("Mago");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel19.setText("Picaro");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, -1));

        jLabel20.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel20.setText("Clerigo");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel21.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel21.setText("Barbaro");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        tab.addTab("Creacion de Personajes", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel22.setText("Seleccione la clase:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 160, -1));

        cb_listar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_listarItemStateChanged(evt);
            }
        });
        jPanel3.add(cb_listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 306, 46));

        jLabel23.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel23.setText("Seleccione el personaje");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jl.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 140, 753, 300));

        tab.addTab("Ver Atributos De un Personaje", jPanel3);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Seleccione el personaje a eliminar:");

        lista_eliminar.setModel(new DefaultListModel());
        lista_eliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lista_eliminarKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(lista_eliminar);

        jButton2.setText("Listar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel25.setText("Para eliminar, selecciona el personaje y presiona la tecla DELETE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel25)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tab.addTab("Eliminar un Personaje", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        tab.addTab("Combate", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_claseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_claseItemStateChanged
        try {
            if (cb_clase.getSelectedIndex() == 0) {
                
                cb_arma.setEnabled(false);
                nv_xp.setEnabled(false);
                cb_magia.setEnabled(false);
                cb_ins.setEnabled(false);
                cant_robo.setEnabled(false);
                
                jt_dios.setEnabled(true);
                jt_invo.setEnabled(true);
                DefaultComboBoxModel modelo_nuevo = (DefaultComboBoxModel) cb_tipo.getModel();
                modelo_nuevo.removeAllElements();
                modelo_nuevo.addElement("Lead");
                cb_tipo.setModel(modelo_nuevo);
                String tipo = cb_tipo.getSelectedItem().toString();
                
            } else if (cb_clase.getSelectedIndex() == 1) {
                jt_dios.setEnabled(false);
                jt_invo.setEnabled(false);
                cb_magia.setEnabled(false);
                cb_ins.setEnabled(false);
                cant_robo.setEnabled(false);
                cb_arma.setEnabled(true);
                nv_xp.setEnabled(true);
                DefaultComboBoxModel modelo_nuevo = (DefaultComboBoxModel) cb_tipo.getModel();
                modelo_nuevo.removeAllElements();
                modelo_nuevo.addElement("Lead");
                modelo_nuevo.addElement("Support");
                modelo_nuevo.addElement("Offensive");
                cb_tipo.setModel(modelo_nuevo);
                String tipo = cb_tipo.getSelectedItem().toString();
                
            } else if (cb_clase.getSelectedIndex() == 2) {
                jt_dios.setEnabled(false);
                jt_invo.setEnabled(false);
                cb_ins.setEnabled(false);
                cant_robo.setEnabled(false);
                cb_arma.setEnabled(false);
                nv_xp.setEnabled(false);
                cb_magia.setEnabled(true);
                DefaultComboBoxModel modelo_nuevo = (DefaultComboBoxModel) cb_tipo.getModel();
                modelo_nuevo.removeAllElements();
                modelo_nuevo.addElement("Support");
                modelo_nuevo.addElement("Tank");
                cb_tipo.setModel(modelo_nuevo);
                String tipo = cb_tipo.getSelectedItem().toString();
                
            } else if (cb_clase.getSelectedIndex() == 3) {
                jt_dios.setEnabled(false);
                jt_invo.setEnabled(false);
                cb_arma.setEnabled(false);
                nv_xp.setEnabled(false);
                cb_magia.setEnabled(false);
                cb_ins.setEnabled(true);
                cant_robo.setEnabled(true);
                DefaultComboBoxModel modelo_nuevo = (DefaultComboBoxModel) cb_tipo.getModel();
                modelo_nuevo.removeAllElements();
                modelo_nuevo.addElement("Spammer");
                modelo_nuevo.addElement("Tank");
                cb_tipo.setModel(modelo_nuevo);
                String tipo = cb_tipo.getSelectedItem().toString();
                
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cb_claseItemStateChanged

    private void bt_crear_personajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crear_personajeMouseClicked
        // TODO add your handling code here:
        String nombre;
        String descrip;
        int estatura;
        int peso;
        int edad;
        int hp = 0;
        DefaultComboBoxModel modelo_nac = (DefaultComboBoxModel) cb_nac.getModel();
        String nac = cb_nac.getSelectedItem().toString();
        String raza = cb_raza.getSelectedItem().toString();
        try {
            nombre = jt_nombre.getText();
            if (cb_raza.getSelectedIndex() == 0) {
                hp = 50 + r.nextInt(60);
            } else if (cb_raza.getSelectedIndex() == 1) {
                hp = 80 + r.nextInt(100);
            } else if (cb_raza.getSelectedIndex() == 2) {
                hp = 50 + r.nextInt(70);
            } else if (cb_raza.getSelectedIndex() == 3) {
                hp = 40 + r.nextInt(75);
            }
            descrip = jt_Descripcion.getText();
            estatura = Integer.parseInt(jft_estatura.getText());
            peso = Integer.parseInt(jft_peso.getText());
            edad = Integer.parseInt(jft_edad.getText());
            
            if (cb_clase.getSelectedIndex() == 0) {
                String dios = jt_dios.getText();
                String invoca = jt_invo.getText();
                int ac = 40;
                int cs = 97;
                String tipo = cb_tipo.getSelectedItem().toString();
                per.add(new Clerigo(dios, invoca, nombre, raza, estatura, peso, edad, ac, cs, hp, descrip, nac, tipo));
                listaClerigos.add(new Clerigo(dios, invoca, nombre, raza, estatura, peso, edad, ac, cs, hp, descrip, nac, tipo));
                administrarClerigo admc = new administrarClerigo("./CLERIGO.ih");
                admc.cargarArchivo();
                admc.setListaClerigos(listaClerigos);
                admc.escribirArchivo();
                JOptionPane.showMessageDialog(this, "Se creó y se guardó exitosamente un Clerigo!");
                jt_dios.setText("");
                jt_invo.setText("");
            } else if (cb_clase.getSelectedIndex() == 1) {
                int ac = 65;
                int cs = 93;
                String tipo = cb_tipo.getSelectedItem().toString();
                String arma = cb_arma.getSelectedItem().toString();
                int niv = Integer.parseInt(nv_xp.getText());
                per.add(new Barbaro(arma, niv, nombre, raza, estatura, peso, edad, ac, cs, hp, descrip, nac, tipo));
                listaBarbaros.add(new Barbaro(arma, niv, nombre, raza, estatura, peso, edad, ac, cs, hp, descrip, nac, tipo));
                administrarBarbaro admb = new administrarBarbaro("./BARBARO.ih");
                admb.cargarArchivo();
                admb.setListaBarbaros(listaBarbaros);
                admb.escribirArchivo();
                JOptionPane.showMessageDialog(this, "Se creó y se guardó exitosamente un Barbaro!");
                nv_xp.setText("");
            } else if (cb_clase.getSelectedIndex() == 2) {
                int ac = 20;
                int cs = 101;
                String tipo = cb_tipo.getSelectedItem().toString();
                String mago = cb_magia.getSelectedItem().toString();
                per.add(new Mago(mago, nombre, raza, estatura, peso, edad, ac, cs, hp, descrip, nac, tipo));
                listaMagos.add(new Mago(mago, nombre, raza, estatura, peso, edad, ac, cs, hp, descrip, nac, tipo));
                administrarMago admM = new administrarMago("./MAGO.ih");
                admM.cargarArchivo();
                admM.setListaMagos(listaMagos);
                admM.escribirArchivo();
                JOptionPane.showMessageDialog(this, "Se creó y se guardó exitosamente un Mago!");
            } else if (cb_clase.getSelectedIndex() == 3) {
                int ac = 50;
                int cs = 80;
                String tipo = cb_tipo.getSelectedItem().toString();
                String instru = cb_ins.getSelectedItem().toString();
                int cant = Integer.parseInt(cant_robo.getText());
                per.add(new Picaro(instru, cant, nombre, raza, estatura, peso, edad, ac, cs, hp, descrip, nac, tipo));
                listaPicaros.add(new Picaro(instru, cant, nombre, raza, estatura, peso, edad, ac, cs, hp, descrip, nac, tipo));
                administrarPicaro admP = new administrarPicaro("./PICARO.ih");
                admP.cargarArchivo();
                admP.setListaPicaros(listaPicaros);
                admP.escribirArchivo();
                JOptionPane.showMessageDialog(this, "Se creó y se guardó exitosamente un Picaro!");
                cant_robo.setText("");
            }
            jt_nombre.setText("");
            jt_Descripcion.setText("");
            jft_edad.setText("");
            jft_peso.setText("");
            jft_estatura.setText("");
            
        } catch (Exception e) {
        }
        

    }//GEN-LAST:event_bt_crear_personajeMouseClicked

    private void cb_listarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_listarItemStateChanged
        // TODO add your handling code here:
        if (cb_listar.getSelectedIndex() == 1) {
            DefaultListModel lista = (DefaultListModel) jl.getModel();
            lista.removeAllElements();
            for (Personaje personaje : per) {
                if (personaje instanceof Barbaro) {
                    lista.addElement(personaje);
                }

            }
        } else if (cb_listar.getSelectedIndex() == 2) {

            DefaultListModel lista = (DefaultListModel) jl.getModel();
            lista.removeAllElements();
            for (Personaje personaje : per) {
                if (personaje instanceof Mago) {
                    lista.addElement(personaje);
                }

            }
        } else if (cb_listar.getSelectedIndex() == 3) {

            DefaultListModel lista = (DefaultListModel) jl.getModel();
            lista.removeAllElements();
            for (Personaje personaje : per) {
                if (personaje instanceof Picaro) {
                    lista.addElement(personaje);
                }

            }
        } else if (cb_listar.getSelectedIndex() == 0) {

            DefaultListModel lista = (DefaultListModel) jl.getModel();
            lista.removeAllElements();
            for (Personaje personaje : per) {
                if (personaje instanceof Clerigo) {
                    lista.addElement(personaje);
                }

            }
        }      
    }//GEN-LAST:event_cb_listarItemStateChanged

    private void tabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tabStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) lista_eliminar.getModel();
        for (Personaje personaje : per) {
            modelo.addElement(personaje);
        }


    }//GEN-LAST:event_jButton2MouseClicked

    private void lista_eliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lista_eliminarKeyPressed
        // TODO add your handling code here:
        try{
        if (evt.getKeyCode() == evt.VK_DELETE) {//evaule la tecla de presiono fue delete
           if (lista_eliminar.getSelectedIndex() >= 0) {//y alguien seleccionado en la JList
               //trapar el modelo Jlist 
               DefaultListModel modelo= (DefaultListModel) lista_eliminar.getModel();
               //para eliminar 
                modelo.remove(lista_eliminar.getSelectedIndex());
                //devuelve el modelo 
                lista_eliminar.setModel(modelo);
//                admB.cargarArchivo();
//                admB.getListaBarbaros().remove(lista_eliminar.getSelectedIndex());
//                admB.escribirArchivo();
//                
//                admM.cargarArchivo();
//                admM.getListaMagos().remove(lista_eliminar.getSelectedIndex());
//                 admM.escribirArchivo();
//                admP.cargarArchivo();
//                 admP.getListaPicaros().remove(lista_eliminar.getSelectedIndex());
//                 admP.escribirArchivo();
//                
//                admc.cargarArchivo();
//                 admc.getListaClerigos().remove(lista_eliminar.getSelectedIndex());
//                 admc.escribirArchivo();
                //el mensaje
                JOptionPane.showMessageDialog(this,
                        "Eliminado exitosamente");
                
            } 
        }
        }catch(Exception e){
            
        }

        
    }//GEN-LAST:event_lista_eliminarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_crear_personaje;
    private javax.swing.JFormattedTextField cant_robo;
    private javax.swing.JComboBox<String> cb_arma;
    private javax.swing.JComboBox<String> cb_clase;
    private javax.swing.JComboBox<String> cb_ins;
    private javax.swing.JComboBox<String> cb_listar;
    private javax.swing.JComboBox<String> cb_magia;
    private javax.swing.JComboBox<String> cb_nac;
    private javax.swing.JComboBox<String> cb_raza;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField jft_edad;
    private javax.swing.JFormattedTextField jft_estatura;
    private javax.swing.JFormattedTextField jft_peso;
    private javax.swing.JList<String> jl;
    private javax.swing.JTextField jt_Descripcion;
    private javax.swing.JTextField jt_dios;
    private javax.swing.JTextField jt_invo;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JList<String> lista_eliminar;
    private javax.swing.JFormattedTextField nv_xp;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
    ArrayList<Clerigo> listaClerigos = new ArrayList();
    ArrayList<Barbaro> listaBarbaros = new ArrayList();
    ArrayList<Mago> listaMagos = new ArrayList();
    ArrayList<Picaro> listaPicaros = new ArrayList();
    
    administrarClerigo admc = new administrarClerigo("./CLERIGO.ih");
    administrarBarbaro admB = new administrarBarbaro("./BARBARO.ih");
    administrarMago admM = new administrarMago("./MAGO.ih");
    administrarPicaro admP = new administrarPicaro("./PICARO.ih");
    
}
