package Prin;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ADMINISTRADOR1
 */
public class Principal extends javax.swing.JFrame {

    static ArrayList<Personaje> per = new ArrayList();
    static Random r = new Random();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

        administrarClerigo admc = new administrarClerigo();
        try {
            admc.cargarArchivo();
        } catch (Exception e) {
        }
        for (Clerigo listaClerigo : admc.getListaClerigos()) {
            listaClerigos.add(listaClerigo);
        }

        DefaultComboBoxModel modelo_clase = (DefaultComboBoxModel) cb_clase.getModel();
        modelo_clase.addElement("Clerigo");
        modelo_clase.addElement("Barbaro");
        modelo_clase.addElement("Mago");
        modelo_clase.addElement("Picaro");
        cb_clase.setModel(modelo_clase);

        DefaultComboBoxModel modelo_listar = (DefaultComboBoxModel) cb_listar.getModel();
        modelo_listar.addElement("Clerigo");
        modelo_listar.addElement("Barbaro");
        modelo_listar.addElement("Mago");
        modelo_listar.addElement("Picaro");
        cb_listar.setModel(modelo_listar);

        DefaultComboBoxModel modelo_nacionalidad = (DefaultComboBoxModel) cb_nac.getModel();
        modelo_nacionalidad.addElement("Norfair");
        modelo_nacionalidad.addElement("Brinstar");
        modelo_nacionalidad.addElement("Maridia");
        modelo_nacionalidad.addElement("Zebes");
        modelo_nacionalidad.addElement("Crateria");
        cb_nac.setModel(modelo_nacionalidad);

        DefaultComboBoxModel modelo_raza = (DefaultComboBoxModel) cb_raza.getModel();
        modelo_raza.addElement("Mediano");
        modelo_raza.addElement("Enano");
        modelo_raza.addElement("Elfo");
        modelo_raza.addElement("Humano");
        cb_raza.setModel(modelo_raza);

        DefaultComboBoxModel modelo_tipo = (DefaultComboBoxModel) cb_tipo.getModel();
        modelo_tipo.addElement("Lead");
        modelo_tipo.addElement("Support");
        modelo_tipo.addElement("Offensive");
        modelo_tipo.addElement("Spammer");
        modelo_tipo.addElement("Tank");
        cb_tipo.setModel(modelo_tipo);

        DefaultComboBoxModel modelo_arma = (DefaultComboBoxModel) cb_arma.getModel();
        modelo_arma.addElement("Pesada");
        modelo_arma.addElement("Ligera");
        modelo_arma.addElement("Escudo");
        cb_arma.setModel(modelo_arma);

        DefaultComboBoxModel modelo_magia = (DefaultComboBoxModel) cb_magia.getModel();
        modelo_magia.addElement("Mago Blanco");
        modelo_magia.addElement("Mago Negro");
        modelo_magia.addElement("Sanador");
        cb_magia.setModel(modelo_magia);

        DefaultComboBoxModel modelo_ins = (DefaultComboBoxModel) cb_ins.getModel();
        modelo_ins.addElement("Amuleto");
        modelo_ins.addElement("Arma");
        modelo_ins.addElement("Piedra");
        cb_ins.setModel(modelo_ins);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cb_raza = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jt_Descripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cb_nac = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<>();
        cb_clase = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jft_estatura = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jft_peso = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jft_edad = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jt_dios = new javax.swing.JTextField();
        jt_invo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nv_xp = new javax.swing.JFormattedTextField();
        cb_arma = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cb_magia = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cb_ins = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cant_robo = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        cb_listar = new javax.swing.JComboBox<>();
        cb_listar_per = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Personajes");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Raza");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Descripcion");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Nacionalidad");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Clase");

        cb_clase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_claseItemStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tipo");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Crear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Estatura");

        jft_estatura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Peso");

        jft_peso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####"))));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Edad");

        jft_edad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("########"))));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Dios");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Invocacion");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Nivel XP");

        nv_xp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Arma");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Tipo de Magia");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Tipo Instrumento");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Cantidad de Robos");

        cant_robo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####"))));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Mago");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Picaro");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Clerigo");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Barbaro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cb_nac, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel11))
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jt_invo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jt_dios, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jft_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jft_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cb_arma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nv_xp)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(49, 49, 49))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb_clase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(26, 26, 26)
                                        .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_raza, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel15)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel8)))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jft_estatura, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(32, 32, 32))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(402, 402, 402)
                                .addComponent(cb_magia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16)
                            .addComponent(cb_ins, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cant_robo))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(cb_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jt_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cb_nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jft_estatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jft_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jft_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jt_dios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_invo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(nv_xp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_magia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(21, 21, 21)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cb_arma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(46, 46, 46)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cb_ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cant_robo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
        );

        tab.addTab("Creacion de Personajes", jPanel1);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Seleccione la clase:");

        cb_listar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_listarItemStateChanged(evt);
            }
        });

        jLabel23.setText("Seleccione el personaje");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_listar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jLabel23)
                    .addComponent(cb_listar_per, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(554, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_listar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_listar_per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        tab.addTab("Ver Atributos De un Personaje", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        tab.addTab("Eliminar un Personaje", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        tab.addTab("Combate", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_claseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_claseItemStateChanged
        try {
            if (cb_clase.getSelectedIndex() == 0) {

                cb_arma.setEnabled(false);
                nv_xp.setEnabled(false);
                cb_magia.setEnabled(false);
                cb_ins.setEnabled(false);
                cant_robo.setEnabled(false);

                jt_dios.setEnabled(true);
                jt_invo.setEnabled(true);
                DefaultComboBoxModel modelo_nuevo = (DefaultComboBoxModel) cb_tipo.getModel();
                modelo_nuevo.removeAllElements();
                modelo_nuevo.addElement("Lead");
                cb_tipo.setModel(modelo_nuevo);
                String tipo = cb_tipo.getSelectedItem().toString();

            } else if (cb_clase.getSelectedIndex() == 1) {
                jt_dios.setEnabled(false);
                jt_invo.setEnabled(false);
                cb_magia.setEnabled(false);
                cb_ins.setEnabled(false);
                cant_robo.setEnabled(false);
                cb_arma.setEnabled(true);
                nv_xp.setEnabled(true);
                DefaultComboBoxModel modelo_nuevo = (DefaultComboBoxModel) cb_tipo.getModel();
                modelo_nuevo.removeAllElements();
                modelo_nuevo.addElement("Lead");
                modelo_nuevo.addElement("Support");
                modelo_nuevo.addElement("Offensive");
                cb_tipo.setModel(modelo_nuevo);
                String tipo = cb_tipo.getSelectedItem().toString();

            } else if (cb_clase.getSelectedIndex() == 2) {
                jt_dios.setEnabled(false);
                jt_invo.setEnabled(false);
                cb_ins.setEnabled(false);
                cant_robo.setEnabled(false);
                cb_arma.setEnabled(false);
                nv_xp.setEnabled(false);
                cb_magia.setEnabled(true);
                DefaultComboBoxModel modelo_nuevo = (DefaultComboBoxModel) cb_tipo.getModel();
                modelo_nuevo.removeAllElements();
                modelo_nuevo.addElement("Support");
                modelo_nuevo.addElement("Tank");
                cb_tipo.setModel(modelo_nuevo);
                String tipo = cb_tipo.getSelectedItem().toString();

            } else if (cb_clase.getSelectedIndex() == 3) {
                jt_dios.setEnabled(false);
                jt_invo.setEnabled(false);
                cb_arma.setEnabled(false);
                nv_xp.setEnabled(false);
                cb_magia.setEnabled(false);
                cb_ins.setEnabled(true);
                cant_robo.setEnabled(true);
                DefaultComboBoxModel modelo_nuevo = (DefaultComboBoxModel) cb_tipo.getModel();
                modelo_nuevo.removeAllElements();
                modelo_nuevo.addElement("Spammer");
                modelo_nuevo.addElement("Tank");
                cb_tipo.setModel(modelo_nuevo);
                String tipo = cb_tipo.getSelectedItem().toString();

            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_cb_claseItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String nombre;
        String descrip;
        int estatura;
        int peso;
        int edad;
        int hp = 0;
        DefaultComboBoxModel modelo_nac = (DefaultComboBoxModel) cb_nac.getModel();
        String nac = cb_nac.getSelectedItem().toString();
        String raza = cb_raza.getSelectedItem().toString();
        try {
            nombre = jt_nombre.getText();
            if (cb_raza.getSelectedIndex() == 0) {
                hp = 50 + r.nextInt(60);
            } else if (cb_raza.getSelectedIndex() == 1) {
                hp = 80 + r.nextInt(100);
            } else if (cb_raza.getSelectedIndex() == 2) {
                hp = 50 + r.nextInt(70);
            } else if (cb_raza.getSelectedIndex() == 3) {
                hp = 40 + r.nextInt(75);
            }
            descrip = jt_Descripcion.getText();
            estatura = Integer.parseInt(jft_estatura.getText());
            peso = Integer.parseInt(jft_peso.getText());
            edad = Integer.parseInt(jft_edad.getText());
            if (cb_clase.getSelectedIndex() == 0) {
                String dios = jt_dios.getText();
                String invoca = jt_invo.getText();
                int ac = 40;
                int cs = 97;
                String tipo = cb_tipo.getSelectedItem().toString();
                per.add(new Clerigo(dios, invoca, nombre, raza, estatura, peso, edad, ac, cs, hp, descrip, nac, tipo));
                administrarClerigo admc = new administrarClerigo("./CLERIGO.ih");
                admc.cargarArchivo();
                admc.setClerigo(new Clerigo(dios, invoca, nombre, raza, estatura, peso, edad, ac, cs, hp, descrip, nac, tipo));
                admc.escribirArchivo();
                JOptionPane.showMessageDialog(this, "Se creó y se guardó exitosamente un Clerigo!");
                jt_dios.setText("");
                jt_invo.setText("");
            } else if (cb_clase.getSelectedIndex() == 1) {
                int ac = 65;
                int cs = 93;
                String tipo = cb_tipo.getSelectedItem().toString();
                String arma = cb_arma.getSelectedItem().toString();
                int niv = Integer.parseInt(nv_xp.getText());
                per.add(new Barbaro(arma, niv, nombre, raza, estatura, peso, edad, ac, cs, hp, descrip, nac, tipo));
                administrarBarbaro admb = new administrarBarbaro("./BARBARO.ih");
                admb.cargarArchivo();
                admb.setBarbaro(new Barbaro(arma, niv, nombre, raza, estatura, peso, edad, ac, cs, hp, descrip, nac, tipo));
                admb.escribirArchivo();
                JOptionPane.showMessageDialog(this, "Se creó y se guardó exitosamente un Barbaro!");
                nv_xp.setText("");
            } else if (cb_clase.getSelectedIndex() == 2) {
                int ac = 20;
                int cs = 101;
                String tipo = cb_tipo.getSelectedItem().toString();
                String mago = cb_magia.getSelectedItem().toString();
                per.add(new Mago(mago, nombre, raza, estatura, peso, edad, ac, cs, hp, descrip, nac, tipo));
                administrarMago admM = new administrarMago("./MAGO.ih");
                admM.cargarArchivo();
                admM.setMago(new Mago(mago, nombre, raza, estatura, peso, edad, ac, cs, hp, descrip, nac, tipo));
                admM.escribirArchivo();
                JOptionPane.showMessageDialog(this, "Se creó y se guardó exitosamente un Mago!");
            } else if (cb_clase.getSelectedIndex() == 3) {
                int ac = 50;
                int cs = 80;
                String tipo = cb_tipo.getSelectedItem().toString();
                String instru = cb_ins.getSelectedItem().toString();
                int cant = Integer.parseInt(cant_robo.getText());
                per.add(new Picaro(instru, cant, nombre, raza, estatura, peso, edad, ac, cs, hp, descrip, nac, tipo));
                administrarPicaro admP = new administrarPicaro("./PICARO.ih");
                admP.cargarArchivo();
                admP.setPicaro(new Picaro(instru, cant, nombre, raza, estatura, peso, edad, ac, cs, hp, descrip, nac, tipo));
                admP.escribirArchivo();
                JOptionPane.showMessageDialog(this, "Se creó y se guardó exitosamente un Picaro!");
                cant_robo.setText("");
            }
            jt_nombre.setText("");
            jt_Descripcion.setText("");
            jft_edad.setText("");
            jft_peso.setText("");
            jft_estatura.setText("");

        } catch (Exception e) {
        }


    }//GEN-LAST:event_jButton1MouseClicked

    private void cb_listarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_listarItemStateChanged
        // TODO add your handling code here:
        if (cb_listar.getSelectedIndex() == 1) {
            
            DefaultComboBoxModel modelo = (DefaultComboBoxModel)cb_listar_per.getModel();
            modelo.removeAllElements();
            for (Personaje personaje : per) {
                if (personaje instanceof Barbaro) {
                    modelo.addElement(personaje);
                }
                
            }
        } else  if (cb_listar.getSelectedIndex() == 2) {
            
            DefaultComboBoxModel modelo = (DefaultComboBoxModel)cb_listar_per.getModel();
            modelo.removeAllElements();
            for (Personaje personaje : per) {
                if (personaje instanceof Mago) {
                    modelo.addElement(personaje);
                }
                
            }
        } else if (cb_listar.getSelectedIndex() == 3) {
            
            DefaultComboBoxModel modelo = (DefaultComboBoxModel)cb_listar_per.getModel();
            modelo.removeAllElements();
            for (Personaje personaje : per) {
                if (personaje instanceof Picaro) {
                    modelo.addElement(personaje);
                }
                
            }
        } else if (cb_listar.getSelectedIndex() == 0) {
            
            DefaultComboBoxModel modelo = (DefaultComboBoxModel)cb_listar_per.getModel();
            modelo.removeAllElements();
            for (Personaje personaje : per) {
                if (personaje instanceof Clerigo) {
                    modelo.addElement(personaje);
                }
                
            }
        }   
    }//GEN-LAST:event_cb_listarItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cant_robo;
    private javax.swing.JComboBox<String> cb_arma;
    private javax.swing.JComboBox<String> cb_clase;
    private javax.swing.JComboBox<String> cb_ins;
    private javax.swing.JComboBox<String> cb_listar;
    private javax.swing.JComboBox<String> cb_listar_per;
    private javax.swing.JComboBox<String> cb_magia;
    private javax.swing.JComboBox<String> cb_nac;
    private javax.swing.JComboBox<String> cb_raza;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JFormattedTextField jft_edad;
    private javax.swing.JFormattedTextField jft_estatura;
    private javax.swing.JFormattedTextField jft_peso;
    private javax.swing.JTextField jt_Descripcion;
    private javax.swing.JTextField jt_dios;
    private javax.swing.JTextField jt_invo;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JFormattedTextField nv_xp;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
    ArrayList<Clerigo> listaClerigos = new ArrayList();
    ArrayList<Barbaro> listaBarbaros = new ArrayList();
    ArrayList<Mago> listaMagos = new ArrayList();
    ArrayList<Picaro> listaPicaros = new ArrayList();
}
